[project]
name = 'Tokenized-Mining-Resource-Extraction-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.environmental-monitoring]
path = 'contracts/environmental-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.extraction-planning]
path = 'contracts/extraction-planning.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
